name: CI

on:
  push:
    branches: [ v2.0.27-onekey ]
  pull_request:
    branches: [ v2.0.27-onekey ]

  workflow_dispatch:

jobs:
  build-installers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.13.1'
      - run: go version
      - uses: docker-practice/actions-setup-docker@master
        with:
          docker_channel: nightly
          docker_nightly_version: snapshot-20201008
      - run: docker version
      - run: go get github.com/karalabe/xgo
      - run: docker pull karalabe/xgo-latest
      - run: cd release
      - run: make all

